### ISSUE TITLE
Provide an initial set of Software Template samples

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/software-templates#38]
## Goal
Provide an initial set of Software Template samples (GPTs _Golden Path Templates_), which use starter projects from the Devfile registry to start. 

## Why
- As a platform engineer, I want a software template sample so that I can quickly provide a GPT for my developers with guardrails.
- As a developer, I want to be able to quickly start a new app
- As a platform engineer, I want an easy way to get started creating a new Backstage plugin 
- 
## Issues included in this epic
- [x] https://github.com/janus-idp/software-templates/issues/39
- [x] https://github.com/janus-idp/software-templates/issues/40
- [x] https://github.com/janus-idp/software-templates/issues/41
- [x] https://github.com/janus-idp/software-templates/issues/42
- [x] https://github.com/janus-idp/software-templates/issues/43
- [x] https://github.com/janus-idp/software-templates/issues/44
- [x] https://github.com/janus-idp/software-templates/issues/45
- [x] https://github.com/janus-idp/software-templates/issues/46
- [x] https://github.com/janus-idp/software-templates/issues/47
- [x] https://github.com/janus-idp/software-templates/issues/48
- [x] https://github.com/janus-idp/software-templates/issues/49
- [x] https://github.com/janus-idp/software-templates/issues/50

**Comment by christophe-f** [comment]
As the backstage plugin is not part of summit, we can close this issue

**Comment by rtaniwa** [comment]
Removed the backstage plugin story. Going to close this one off now. @serenamarie125 if you have any concerns with what was delivered, feel free to reopen.
